load("//:proof.bzl", "klibrary")

klibrary(
  name = "only-this-signer-diffs-files",
  srcs = ["only-this-signer-diffs.k"],
  deps = [
      "//protocol-correctness/lib/language:base-types-files",
  ],
  visibility = ["//visibility:public"],
)

