load("//:proof.bzl", "klibrary")

klibrary(
  name = "equality-without-substitution-files",
  srcs = ["equality-without-substitution.k"],
  deps = [
  ],
  visibility = ["//visibility:public"],
)

klibrary(
  name = "formula-expansion-files",
  srcs = ["formula-expansion.k"],
  deps = [
  ],
  visibility = ["//visibility:public"],
)

